FROM gcr.io/cloud-builders/kubectl
ENV KUBE_LATEST_VERSION="v1.13.3"
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl -o /builder/google-cloud-sdk/bin//kubectl
