steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:latest"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.7"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.7"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.7"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.6"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.6"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.5"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.5"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.4"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.4"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.3"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.3"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.2"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.2"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.1"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.1"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.2.0"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.2.0"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.1.4"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.1.4"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.1.3"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.1.3"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.1.2"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.1.2"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.1.1"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.1.1"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "."
      - "--tag=gcr.io/$PROJECT_ID/ballerina:v1.1.0"
      - "--file=Dockerfile"
      - "--build-arg"
      - "ballerina_version=1.1.0"

images:
  - "gcr.io/$PROJECT_ID/ballerina:latest"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.7"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.6"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.5"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.4"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.3"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.2"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.1"
  - "gcr.io/$PROJECT_ID/ballerina:v1.2.0"
  - "gcr.io/$PROJECT_ID/ballerina:v1.1.4"
  - "gcr.io/$PROJECT_ID/ballerina:v1.1.3"
  - "gcr.io/$PROJECT_ID/ballerina:v1.1.2"
  - "gcr.io/$PROJECT_ID/ballerina:v1.1.1"
  - "gcr.io/$PROJECT_ID/ballerina:v1.1.0"

timeout: 3600s

tags: ["cloud-builders-community"]
